require('keymappings.keymappings')
require('keymappings.dashboard')
require('keymappings.sidebar')
-- require('keymappings.coc')
require('keymappings.neogit')
require('keymappings.trouble')
require('keymappings.lsp')
require('keymappings.lines-lsp')
require('keymappings.focus')
